version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev

    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend/backend

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile

    volumes:
      - ./scraper:/scraper/scraper
    command: celery -A tasks worker --loglevel=info

  celery-beat:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    volumes:
      - ./scraper:/scraper
      - ./shared:/shared

    command: celery -A tasks beat --loglevel=info
