version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile.dev

    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./.env:/.env

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile

    volumes:
      - ./scraper:/scraper/scraper
      - ./.env:/.env
    command: celery -A tasks worker --loglevel=info

  celery-beat:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    volumes:
      - ./scraper:/scraper
      - ./shared:/shared
      - ./.env:/.env

    command: celery -A tasks beat --loglevel=info
