"""added new columns to jobs

Revision ID: 1f4caad00eb5
Revises: 3b954792b00a
Create Date: 2025-06-07 22:35:50.850154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f4caad00eb5"
down_revision: Union[str, None] = "3b954792b00a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add with default and allow null temporarily
    op.add_column(
        "users",
        sa.Column(
            "is_active", sa.Boolean(), nullable=True, server_default=sa.text("true")
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_admin", sa.Boolean(), nullable=True, server_default=sa.text("false")
        ),
    )

    # Step 2: Now change them to NOT NULL
    op.alter_column("users", "is_active", nullable=False)
    op.alter_column("users", "is_admin", nullable=False)

    # Optional: clean up default if you want app-level control
    op.alter_column("users", "is_active", server_default=None)
    op.alter_column("users", "is_admin", server_default=None)

    # These are fine as-is
    op.add_column(
        "users", sa.Column("profile_picture", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "users", sa.Column("last_login", sa.DateTime(timezone=True), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login")
    op.drop_column("users", "profile_picture")
    op.drop_column("users", "is_admin")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
