"""Make password nullable for Google OAuth users

Revision ID: c062c4773f1e
Revises: fa266ba0037d
Create Date: 2025-06-14 15:44:52.820685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c062c4773f1e'
down_revision: Union[str, None] = 'fa266ba0037d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=100), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
